// Copyright Epic Games, Inc. All Rights Reserved.

#include "BlueprintTextExportService.h"

#include "Dom/JsonObject.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Engine/Blueprint.h"
#include "HAL/FileManager.h"
#include "K2Node.h"
#include "K2Node_Event.h"
#include "K2Node_FunctionEntry.h"
#include "K2Node_Knot.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Misc/FileHelper.h"
#include "Misc/PackageName.h"
#include "Misc/Paths.h"
#include "Misc/SecureHash.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"
#include "UObject/Package.h"

DEFINE_LOG_CATEGORY_STATIC(LogBlueprintTextExporter, Log, All);

namespace UE::BlueprintTextExporter
{
	struct FExportParameter
	{
		FString Name;
		FString Value;
	};

	struct FExportLink;

	struct FExportNode
	{
		FString Id;
		FString Title;
		FString NodeClass;
		FString GraphName;
		TArray<FExportParameter> Parameters;
		TArray<FExportLink> Outputs;
	};

	struct FExportLink
	{
		FString Label;
		TArray<TSharedPtr<FExportNode>> Targets;
		TArray<FString> LoopTargets;
	};

	struct FGraphExport
	{
		FString GraphName;
		FString GraphType;
		TArray<TSharedPtr<FExportNode>> Roots;
	};

	struct FInlineContext
	{
		TSet<const UEdGraphNode*> VisitingNodes;
	};

	struct FTraversalContext
	{
		TSet<const UEdGraphNode*> NodeStack;
	};

	static bool IsExecPin(const UEdGraphPin* InPin)
	{
		return InPin != nullptr && InPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec;
	}

	static bool IsInputPin(const UEdGraphPin* InPin)
	{
		return InPin != nullptr && InPin->Direction == EGPD_Input;
	}

	static bool IsOutputPin(const UEdGraphPin* InPin)
	{
		return InPin != nullptr && InPin->Direction == EGPD_Output;
	}

	static bool IsPureNode(const UEdGraphNode* InNode)
	{
		if (const UK2Node* K2Node = Cast<UK2Node>(InNode))
		{
			return K2Node->IsNodePure();
		}

		return false;
	}

	static FString NormalizeWhitespace(FString InValue)
	{
		InValue.ReplaceInline(TEXT("\r"), TEXT(" "));
		InValue.ReplaceInline(TEXT("\n"), TEXT(" "));
		InValue.TrimStartAndEndInline();
		return InValue;
	}

	static FString GetNodeTitle(const UEdGraphNode* InNode)
	{
		if (InNode == nullptr)
		{
			return TEXT("<null>");
		}

		return NormalizeWhitespace(InNode->GetNodeTitle(ENodeTitleType::ListView).ToString());
	}

	static FString GetPinDisplayName(const UEdGraphPin* InPin)
	{
		if (InPin == nullptr)
		{
			return TEXT("Pin");
		}

		const FString FriendlyName = NormalizeWhitespace(InPin->GetDisplayName().ToString());
		return FriendlyName.IsEmpty() ? InPin->PinName.ToString() : FriendlyName;
	}

	static FString GetPinLiteralValue(const UEdGraphPin* InPin)
	{
		if (InPin == nullptr)
		{
			return FString();
		}

		if (InPin->DefaultObject != nullptr)
		{
			return InPin->DefaultObject->GetName();
		}

		const FString DefaultTextValue = InPin->DefaultTextValue.ToString();
		if (!DefaultTextValue.IsEmpty())
		{
			return NormalizeWhitespace(DefaultTextValue);
		}

		if (!InPin->DefaultValue.IsEmpty() && InPin->DefaultValue != InPin->AutogeneratedDefaultValue)
		{
			return NormalizeWhitespace(InPin->DefaultValue);
		}

		return FString();
	}

	static FString DescribePureNode(const UEdGraphNode* InNode, FInlineContext& InContext);

	static FString DescribePinValue(const UEdGraphPin* InPin, FInlineContext& InContext)
	{
		if (InPin == nullptr)
		{
			return FString();
		}

		TArray<FString> Parts;
		for (const UEdGraphPin* LinkedPin : InPin->LinkedTo)
		{
			if (LinkedPin == nullptr)
			{
				continue;
			}

			Parts.Add(DescribePureNode(LinkedPin->GetOwningNode(), InContext));
		}

		if (Parts.Num() > 0)
		{
			return FString::Join(Parts, TEXT(", "));
		}

		return GetPinLiteralValue(InPin);
	}

	static FString DescribePureNode(const UEdGraphNode* InNode, FInlineContext& InContext)
	{
		if (InNode == nullptr)
		{
			return TEXT("<null>");
		}

		if (InContext.VisitingNodes.Contains(InNode))
		{
			return FString::Printf(TEXT("[recursive:%s]"), *GetNodeTitle(InNode));
		}

		const bool bPureNode = IsPureNode(InNode);
		if (!bPureNode)
		{
			return GetNodeTitle(InNode);
		}

		InContext.VisitingNodes.Add(InNode);

		TArray<FString> ParameterParts;
		for (const UEdGraphPin* Pin : InNode->Pins)
		{
			if (Pin == nullptr || Pin->bHidden || !IsInputPin(Pin) || IsExecPin(Pin))
			{
				continue;
			}

			const FString Value = DescribePinValue(Pin, InContext);
			if (!Value.IsEmpty())
			{
				ParameterParts.Add(FString::Printf(TEXT("%s=%s"), *GetPinDisplayName(Pin), *Value));
			}
		}

		InContext.VisitingNodes.Remove(InNode);

		const FString Title = GetNodeTitle(InNode);
		return ParameterParts.Num() > 0
			? FString::Printf(TEXT("%s(%s)"), *Title, *FString::Join(ParameterParts, TEXT(", ")))
			: FString::Printf(TEXT("%s()"), *Title);
	}

	static void ResolveExecTargetsRecursive(const UEdGraphPin* InPin, TArray<const UEdGraphNode*>& OutNodes, TSet<const UEdGraphPin*>& InOutVisitedPins)
	{
		if (InPin == nullptr || InOutVisitedPins.Contains(InPin))
		{
			return;
		}

		InOutVisitedPins.Add(InPin);

		const UEdGraphNode* OwnerNode = InPin->GetOwningNode();
		if (const UK2Node_Knot* KnotNode = Cast<UK2Node_Knot>(OwnerNode))
		{
			for (const UEdGraphPin* KnotPin : KnotNode->Pins)
			{
				if (KnotPin == nullptr || KnotPin == InPin || !IsExecPin(KnotPin))
				{
					continue;
				}

				for (const UEdGraphPin* LinkedPin : KnotPin->LinkedTo)
				{
					ResolveExecTargetsRecursive(LinkedPin, OutNodes, InOutVisitedPins);
				}
			}

			return;
		}

		if (OwnerNode != nullptr)
		{
			OutNodes.AddUnique(OwnerNode);
		}
	}

	static TArray<const UEdGraphNode*> ResolveExecTargets(const UEdGraphPin* InPin)
	{
		TArray<const UEdGraphNode*> Nodes;
		TSet<const UEdGraphPin*> VisitedPins;

		if (InPin == nullptr)
		{
			return Nodes;
		}

		for (const UEdGraphPin* LinkedPin : InPin->LinkedTo)
		{
			ResolveExecTargetsRecursive(LinkedPin, Nodes, VisitedPins);
		}

		return Nodes;
	}

	static bool HasLinkedExecOutput(const UEdGraphNode* InNode)
	{
		if (InNode == nullptr)
		{
			return false;
		}

		for (const UEdGraphPin* Pin : InNode->Pins)
		{
			if (Pin != nullptr && IsOutputPin(Pin) && IsExecPin(Pin) && Pin->LinkedTo.Num() > 0)
			{
				return true;
			}
		}

		return false;
	}

	static bool HasLinkedExecInput(const UEdGraphNode* InNode)
	{
		if (InNode == nullptr)
		{
			return false;
		}

		for (const UEdGraphPin* Pin : InNode->Pins)
		{
			if (Pin != nullptr && IsInputPin(Pin) && IsExecPin(Pin) && Pin->LinkedTo.Num() > 0)
			{
				return true;
			}
		}

		return false;
	}

	static bool IsExportRootNode(const UEdGraphNode* InNode)
	{
		if (InNode == nullptr || Cast<UK2Node_Knot>(InNode) != nullptr)
		{
			return false;
		}

		if (Cast<UK2Node_Event>(InNode) != nullptr || Cast<UK2Node_FunctionEntry>(InNode) != nullptr)
		{
			return true;
		}

		return HasLinkedExecOutput(InNode) && !HasLinkedExecInput(InNode);
	}

	static TArray<const UEdGraphNode*> CollectRootNodes(const UEdGraph* InGraph)
	{
		TArray<const UEdGraphNode*> RootNodes;
		if (InGraph == nullptr)
		{
			return RootNodes;
		}

		for (const UEdGraphNode* Node : InGraph->Nodes)
		{
			if (IsExportRootNode(Node))
			{
				RootNodes.Add(Node);
			}
		}

		RootNodes.Sort(
			[](const UEdGraphNode& A, const UEdGraphNode& B)
			{
				return A.NodePosY == B.NodePosY ? A.NodePosX < B.NodePosX : A.NodePosY < B.NodePosY;
			});

		return RootNodes;
	}

	static FString MakeNodeId(const UEdGraphNode* InNode)
	{
		if (InNode == nullptr)
		{
			return TEXT("InvalidNode");
		}

		if (InNode->NodeGuid.IsValid())
		{
			return InNode->NodeGuid.ToString(EGuidFormats::DigitsWithHyphensLower);
		}

		return FMD5::HashAnsiString(*InNode->GetPathName());
	}

	static TSharedPtr<FExportNode> BuildExportNode(const UEdGraphNode* InNode, const UEdGraph* InGraph, FTraversalContext& InContext)
	{
		if (InNode == nullptr)
		{
			return nullptr;
		}

		if (InContext.NodeStack.Contains(InNode))
		{
			return nullptr;
		}

		InContext.NodeStack.Add(InNode);

		TSharedPtr<FExportNode> ExportNode = MakeShared<FExportNode>();
		ExportNode->Id = MakeNodeId(InNode);
		ExportNode->Title = GetNodeTitle(InNode);
		ExportNode->NodeClass = InNode->GetClass()->GetName();
		ExportNode->GraphName = InGraph != nullptr ? InGraph->GetName() : FString();

		FInlineContext InlineContext;
		for (const UEdGraphPin* Pin : InNode->Pins)
		{
			if (Pin == nullptr || Pin->bHidden || !IsInputPin(Pin) || IsExecPin(Pin))
			{
				continue;
			}

			const FString Value = DescribePinValue(Pin, InlineContext);
			if (!Value.IsEmpty())
			{
				FExportParameter& Parameter = ExportNode->Parameters.AddDefaulted_GetRef();
				Parameter.Name = GetPinDisplayName(Pin);
				Parameter.Value = Value;
			}
		}

		for (const UEdGraphPin* Pin : InNode->Pins)
		{
			if (Pin == nullptr || !IsOutputPin(Pin) || !IsExecPin(Pin))
			{
				continue;
			}

			FExportLink Link;
			Link.Label = GetPinDisplayName(Pin);

			for (const UEdGraphNode* TargetNode : ResolveExecTargets(Pin))
			{
				if (TargetNode == nullptr)
				{
					continue;
				}

				if (InContext.NodeStack.Contains(TargetNode))
				{
					Link.LoopTargets.Add(GetNodeTitle(TargetNode));
					continue;
				}

				if (TSharedPtr<FExportNode> ChildNode = BuildExportNode(TargetNode, InGraph, InContext))
				{
					Link.Targets.Add(ChildNode);
				}
			}

			if (Link.Targets.Num() > 0 || Link.LoopTargets.Num() > 0)
			{
				ExportNode->Outputs.Add(MoveTemp(Link));
			}
		}

		InContext.NodeStack.Remove(InNode);
		return ExportNode;
	}

	static FString FormatNodeLine(const FExportNode& InNode)
	{
		if (InNode.Parameters.Num() == 0)
		{
			return InNode.Title;
		}

		TArray<FString> Parts;
		for (const FExportParameter& Parameter : InNode.Parameters)
		{
			Parts.Add(FString::Printf(TEXT("%s=%s"), *Parameter.Name, *Parameter.Value));
		}

		return FString::Printf(TEXT("%s (%s)"), *InNode.Title, *FString::Join(Parts, TEXT(", ")));
	}

	static void AppendNodeText(const TSharedPtr<FExportNode>& InNode, const FString& InIndent, TArray<FString>& OutLines)
	{
		if (!InNode.IsValid())
		{
			return;
		}

		OutLines.Add(InIndent + FormatNodeLine(*InNode));

		for (const FExportLink& Link : InNode->Outputs)
		{
			OutLines.Add(FString::Printf(TEXT("%s  %s ->"), *InIndent, *Link.Label));

			for (const TSharedPtr<FExportNode>& Target : Link.Targets)
			{
				AppendNodeText(Target, InIndent + TEXT("    "), OutLines);
			}

			for (const FString& LoopTarget : Link.LoopTargets)
			{
				OutLines.Add(FString::Printf(TEXT("%s    [Loop] %s"), *InIndent, *LoopTarget));
			}
		}
	}

	static TSharedPtr<FJsonObject> BuildNodeJson(const TSharedPtr<FExportNode>& InNode)
	{
		if (!InNode.IsValid())
		{
			return nullptr;
		}

		TSharedPtr<FJsonObject> NodeObject = MakeShared<FJsonObject>();
		NodeObject->SetStringField(TEXT("id"), InNode->Id);
		NodeObject->SetStringField(TEXT("title"), InNode->Title);
		NodeObject->SetStringField(TEXT("nodeClass"), InNode->NodeClass);
		NodeObject->SetStringField(TEXT("graphName"), InNode->GraphName);

		TArray<TSharedPtr<FJsonValue>> Parameters;
		for (const FExportParameter& Parameter : InNode->Parameters)
		{
			TSharedPtr<FJsonObject> ParameterObject = MakeShared<FJsonObject>();
			ParameterObject->SetStringField(TEXT("name"), Parameter.Name);
			ParameterObject->SetStringField(TEXT("value"), Parameter.Value);
			Parameters.Add(MakeShared<FJsonValueObject>(ParameterObject));
		}
		NodeObject->SetArrayField(TEXT("parameters"), Parameters);

		TArray<TSharedPtr<FJsonValue>> OutputArray;
		for (const FExportLink& Output : InNode->Outputs)
		{
			TSharedPtr<FJsonObject> OutputObject = MakeShared<FJsonObject>();
			OutputObject->SetStringField(TEXT("label"), Output.Label);

			TArray<TSharedPtr<FJsonValue>> TargetArray;
			for (const TSharedPtr<FExportNode>& Target : Output.Targets)
			{
				TargetArray.Add(MakeShared<FJsonValueObject>(BuildNodeJson(Target)));
			}
			OutputObject->SetArrayField(TEXT("targets"), TargetArray);

			TArray<TSharedPtr<FJsonValue>> LoopArray;
			for (const FString& LoopTarget : Output.LoopTargets)
			{
				LoopArray.Add(MakeShared<FJsonValueString>(LoopTarget));
			}
			OutputObject->SetArrayField(TEXT("loopTargets"), LoopArray);

			OutputArray.Add(MakeShared<FJsonValueObject>(OutputObject));
		}
		NodeObject->SetArrayField(TEXT("outputs"), OutputArray);

		return NodeObject;
	}

	static FString GetGraphType(const UBlueprint* InBlueprint, const UEdGraph* InGraph)
	{
		if (InBlueprint == nullptr || InGraph == nullptr)
		{
			return TEXT("Unknown");
		}

		if (InBlueprint->UbergraphPages.Contains(const_cast<UEdGraph*>(InGraph)))
		{
			return TEXT("EventGraph");
		}

		if (InBlueprint->FunctionGraphs.Contains(const_cast<UEdGraph*>(InGraph)))
		{
			return TEXT("FunctionGraph");
		}

		if (InBlueprint->MacroGraphs.Contains(const_cast<UEdGraph*>(InGraph)))
		{
			return TEXT("MacroGraph");
		}

		return TEXT("SubGraph");
	}

	static TArray<FGraphExport> BuildGraphExports(const UBlueprint* InBlueprint)
	{
		TArray<FGraphExport> GraphExports;
		if (InBlueprint == nullptr)
		{
			return GraphExports;
		}

		TArray<UEdGraph*> AllGraphs;
		const_cast<UBlueprint*>(InBlueprint)->GetAllGraphs(AllGraphs);

		AllGraphs.Sort(
			[](const UEdGraph& A, const UEdGraph& B)
			{
				return A.GetName() < B.GetName();
			});

		for (UEdGraph* Graph : AllGraphs)
		{
			if (Graph == nullptr)
			{
				continue;
			}

			const TArray<const UEdGraphNode*> RootNodes = CollectRootNodes(Graph);
			if (RootNodes.Num() == 0)
			{
				continue;
			}

			FGraphExport& GraphExport = GraphExports.AddDefaulted_GetRef();
			GraphExport.GraphName = Graph->GetName();
			GraphExport.GraphType = GetGraphType(InBlueprint, Graph);

			for (const UEdGraphNode* RootNode : RootNodes)
			{
				FTraversalContext TraversalContext;
				if (TSharedPtr<FExportNode> RootExport = BuildExportNode(RootNode, Graph, TraversalContext))
				{
					GraphExport.Roots.Add(RootExport);
				}
			}
		}

		return GraphExports;
	}

	static FString BuildTextOutput(const UBlueprint* InBlueprint, const TArray<FGraphExport>& InGraphs)
	{
		TArray<FString> Lines;
		Lines.Add(FString::Printf(TEXT("Blueprint: %s"), *InBlueprint->GetPathName()));
		Lines.Add(FString::Printf(TEXT("BlueprintClass: %s"), *InBlueprint->GetClass()->GetName()));
		Lines.Add(FString::Printf(TEXT("GeneratedClass: %s"), InBlueprint->GeneratedClass ? *InBlueprint->GeneratedClass->GetPathName() : TEXT("<none>")));
		Lines.Add(TEXT(""));

		for (const FGraphExport& Graph : InGraphs)
		{
			Lines.Add(FString::Printf(TEXT("[%s] %s"), *Graph.GraphType, *Graph.GraphName));
			for (const TSharedPtr<FExportNode>& RootNode : Graph.Roots)
			{
				AppendNodeText(RootNode, TEXT("  "), Lines);
			}
			Lines.Add(TEXT(""));
		}

		return FString::Join(Lines, TEXT("\r\n"));
	}

	static FString BuildJsonOutput(const UBlueprint* InBlueprint, const TArray<FGraphExport>& InGraphs)
	{
		TSharedPtr<FJsonObject> RootObject = MakeShared<FJsonObject>();
		RootObject->SetStringField(TEXT("blueprintPath"), InBlueprint->GetPathName());
		RootObject->SetStringField(TEXT("blueprintName"), InBlueprint->GetName());
		RootObject->SetStringField(TEXT("assetClass"), InBlueprint->GetClass()->GetName());
		RootObject->SetStringField(TEXT("generatedClass"), InBlueprint->GeneratedClass ? InBlueprint->GeneratedClass->GetPathName() : FString());

		TArray<TSharedPtr<FJsonValue>> GraphArray;
		for (const FGraphExport& Graph : InGraphs)
		{
			TSharedPtr<FJsonObject> GraphObject = MakeShared<FJsonObject>();
			GraphObject->SetStringField(TEXT("graphName"), Graph.GraphName);
			GraphObject->SetStringField(TEXT("graphType"), Graph.GraphType);

			TArray<TSharedPtr<FJsonValue>> RootArray;
			for (const TSharedPtr<FExportNode>& RootNode : Graph.Roots)
			{
				RootArray.Add(MakeShared<FJsonValueObject>(BuildNodeJson(RootNode)));
			}
			GraphObject->SetArrayField(TEXT("roots"), RootArray);
			GraphArray.Add(MakeShared<FJsonValueObject>(GraphObject));
		}

		RootObject->SetArrayField(TEXT("graphs"), GraphArray);

		FString JsonOutput;
		const TSharedRef<TJsonWriter<>> Writer = TJsonWriterFactory<>::Create(&JsonOutput);
		FJsonSerializer::Serialize(RootObject.ToSharedRef(), Writer);
		return JsonOutput;
	}

	static void BuildExportPaths(const UBlueprint* InBlueprint, FString& OutTextPath, FString& OutJsonPath)
	{
		const FString PackageName = InBlueprint->GetOutermost()->GetName();
		FString RelativeDirectory = FPackageName::GetLongPackagePath(PackageName);
		RelativeDirectory.RemoveFromStart(TEXT("/"));
		RelativeDirectory.ReplaceInline(TEXT("/"), TEXT("\\"));

		const FString ExportDirectory = FPaths::Combine(FPaths::ProjectSavedDir(), TEXT("BlueprintExports"), RelativeDirectory);
		IFileManager::Get().MakeDirectory(*ExportDirectory, true);

		const FString AssetName = FPackageName::GetLongPackageAssetName(PackageName);
		OutTextPath = FPaths::Combine(ExportDirectory, AssetName + TEXT(".txt"));
		OutJsonPath = FPaths::Combine(ExportDirectory, AssetName + TEXT(".json"));
	}
}

bool FBlueprintTextExportService::ExportBlueprint(UBlueprint* InBlueprint, FString& OutTextPath, FString& OutJsonPath, FString& OutErrorMessage)
{
	using namespace UE::BlueprintTextExporter;

	if (InBlueprint == nullptr)
	{
		OutErrorMessage = TEXT("Blueprint is null.");
		return false;
	}

	const TArray<FGraphExport> GraphExports = BuildGraphExports(InBlueprint);
	if (GraphExports.Num() == 0)
	{
		OutErrorMessage = TEXT("No executable Blueprint graphs were found.");
		return false;
	}

	BuildExportPaths(InBlueprint, OutTextPath, OutJsonPath);

	const FString TextOutput = BuildTextOutput(InBlueprint, GraphExports);
	const FString JsonOutput = BuildJsonOutput(InBlueprint, GraphExports);

	if (!FFileHelper::SaveStringToFile(TextOutput, *OutTextPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
	{
		OutErrorMessage = FString::Printf(TEXT("Failed to save text output to '%s'."), *OutTextPath);
		return false;
	}

	if (!FFileHelper::SaveStringToFile(JsonOutput, *OutJsonPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
	{
		OutErrorMessage = FString::Printf(TEXT("Failed to save JSON output to '%s'."), *OutJsonPath);
		return false;
	}

	return true;
}
